### ISSUE TITLE
Meson wrap file does not download packages with https url

### ISSUE THREAD

**Issue by minh7a6** [xpack-dev-tools/meson-build-xpack#6]
Hi @ilg-ul, 

First of all, thanks for the hard work repackaging this tool to the xpack, it helps a lot for cross-platform development :). However, I encountered an issue where the meson packaged in this tool will refuse to download wrap packages due to SSL error. 
It may be because the Python package in this tool does not have OpenSSL packaged with the Python binary. I tested with the meson built upstream and it works fine.

Thanks!

**Comment by ilg-ul** [comment]
Hi @minh7a6,

Sorry for the troubles you encountered. You are right, the embedded Python may not have all features enabled.

Can you enable some logging to get more details on the failed operation?

**Comment by minh7a6** [comment]
Hi @ilg-ul,
I have instantiated the environment with hello-world project, use `xpack/.bin/meson wrap install gtest`, this is what I got:
```Traceback (most recent call last):
  File "/Host/home/ilg/Work/meson-build-0.60.3-1/linux-x64/install/meson-build/lib/python3.10/urllib/request.py", line 1348, in do_open
  File "/Host/home/ilg/Work/meson-build-0.60.3-1/linux-x64/install/meson-build/lib/python3.10/http/client.py", line 1282, in request
  File "/Host/home/ilg/Work/meson-build-0.60.3-1/linux-x64/install/meson-build/lib/python3.10/http/client.py", line 1328, in _send_request
  File "/Host/home/ilg/Work/meson-build-0.60.3-1/linux-x64/install/meson-build/lib/python3.10/http/client.py", line 1277, in endheaders
  File "/Host/home/ilg/Work/meson-build-0.60.3-1/linux-x64/install/meson-build/lib/python3.10/http/client.py", line 1037, in _send_output
  File "/Host/home/ilg/Work/meson-build-0.60.3-1/linux-x64/install/meson-build/lib/python3.10/http/client.py", line 975, in send
  File "/Host/home/ilg/Work/meson-build-0.60.3-1/linux-x64/install/meson-build/lib/python3.10/http/client.py", line 1454, in connect
  File "/Host/home/ilg/Work/meson-build-0.60.3-1/linux-x64/install/meson-build/lib/python3.10/ssl.py", line 512, in wrap_socket
  File "/Host/home/ilg/Work/meson-build-0.60.3-1/linux-x64/install/meson-build/lib/python3.10/ssl.py", line 1070, in _create
  File "/Host/home/ilg/Work/meson-build-0.60.3-1/linux-x64/install/meson-build/lib/python3.10/ssl.py", line 1341, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Host/home/ilg/Work/meson-build-0.60.3-1/linux-x64/install/meson-build/lib/python3.10/mesonbuild/mesonmain.py", line 138, in run
  File "/Host/home/ilg/Work/meson-build-0.60.3-1/linux-x64/install/meson-build/lib/python3.10/mesonbuild/wrap/wraptool.py", line 223, in run
  File "/Host/home/ilg/Work/meson-build-0.60.3-1/linux-x64/install/meson-build/lib/python3.10/mesonbuild/wrap/wraptool.py", line 99, in install
  File "/Host/home/ilg/Work/meson-build-0.60.3-1/linux-x64/install/meson-build/lib/python3.10/mesonbuild/wrap/wraptool.py", line 82, in get_latest_version
  File "/Host/home/ilg/Work/meson-build-0.60.3-1/linux-x64/install/meson-build/lib/python3.10/mesonbuild/wrap/wraptool.py", line 62, in get_releases
  File "/Host/home/ilg/Work/meson-build-0.60.3-1/linux-x64/install/meson-build/lib/python3.10/urllib/request.py", line 216, in urlopen
  File "/Host/home/ilg/Work/meson-build-0.60.3-1/linux-x64/install/meson-build/lib/python3.10/urllib/request.py", line 519, in open
  File "/Host/home/ilg/Work/meson-build-0.60.3-1/linux-x64/install/meson-build/lib/python3.10/urllib/request.py", line 536, in _open
  File "/Host/home/ilg/Work/meson-build-0.60.3-1/linux-x64/install/meson-build/lib/python3.10/urllib/request.py", line 496, in _call_chain
  File "/Host/home/ilg/Work/meson-build-0.60.3-1/linux-x64/install/meson-build/lib/python3.10/urllib/request.py", line 1391, in https_open
  File "/Host/home/ilg/Work/meson-build-0.60.3-1/linux-x64/install/meson-build/lib/python3.10/urllib/request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>```

**Comment by ilg-ul** [comment]
Thank you for these extra details. I'll try to investigate, but it might take some time, I'm in the middle of some other releases.

**Comment by ilg-ul** [comment]
I tried to reproduce the problem, but did not get too far:

```console
% xpacks/.bin/meson wrap install gtest
Subprojects dir not found. Run this script in your source root directory.
```

My experience with Python is limited, I don't know how to proceed... :-(

I used meson 1.4.2-1.1.

**Comment by minh7a6** [comment]
Hi @ilg-ul,

I forgot to add but I think you need to create `subproject` folder in your project directory before you do `meson wrap...`.

**Comment by ilg-ul** [comment]
I confirm the issue:

```console
% mkdir subprojects                   
ilg@wksi ppp % xpacks/.bin/meson wrap install gtest

ERROR: WrapDB connection failed to https://wrapdb.mesonbuild.com/v2/releases.json with error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>.

    To allow connecting anyway, pass `--allow-insecure`.
ilg@wksi ppp % xpacks/.bin/meson wrap install gtest --allow-insecure
WARNING: WrapDB connection failed to https://wrapdb.mesonbuild.com/v2/releases.json with error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>.

    Proceeding without authentication.

ERROR: WrapDB connection failed to https://wrapdb.mesonbuild.com/v2/releases.json with error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
```

The issue seems to be caused by a missing certificate. 

For the moment I do not know how to add it to the build. :-(

I'll try to take a look at openssl, maybe I get a hint from there.

**Comment by ilg-ul** [comment]
Fixed in 1.5.2-1 on 2025-01-03.
